
import { db } from "../server/db";
import { movies } from "@shared/schema";

async function seed() {
  console.log("Seeding database with sample data...");
  
  const sampleMovies = [
    // Featured movie
    {
      title: "Captain America: Brave New World",
      description: "After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.",
      year: 2025,
      duration: 119,
      rating: 7.2,
      quality: "HD",
      poster: "https://img.cdno.my.id/cover/w_1280/h_405/captain-america-brave-new-world-1630858461.jpg",
      backdrop: "https://img.cdno.my.id/cover/w_1280/h_405/captain-america-brave-new-world-1630858461.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_1mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample1",
      genres: ["Action", "Thriller", "Sci-Fi"],
      countries: ["United States"],
      type: "movie",
      featured: true
    },
    // 2024 Movies
    {
      title: "Dune: Part Two",
      description: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
      year: 2024,
      duration: 166,
      rating: 8.5,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_2mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample2",
      genres: ["Sci-Fi", "Adventure", "Drama"],
      countries: ["United States"],
      type: "movie",
      featured: false
    },
    {
      title: "Oppenheimer",
      description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
      year: 2023,
      duration: 180,
      rating: 8.3,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_3mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample3",
      genres: ["Biography", "Drama", "History"],
      countries: ["United States"],
      type: "movie",
      featured: false
    },
    {
      title: "Barbie",
      description: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land.",
      year: 2023,
      duration: 114,
      rating: 6.9,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_4mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample4",
      genres: ["Comedy", "Adventure", "Fantasy"],
      countries: ["United States"],
      type: "movie",
      featured: false
    },
    {
      title: "John Wick: Chapter 4",
      description: "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy.",
      year: 2023,
      duration: 169,
      rating: 7.7,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_5mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample5",
      genres: ["Action", "Thriller", "Crime"],
      countries: ["United States"],
      type: "movie",
      featured: false
    },
    {
      title: "Spider-Man: Across the Spider-Verse",
      description: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
      year: 2023,
      duration: 140,
      rating: 8.7,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_6mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample6",
      genres: ["Animation", "Action", "Adventure"],
      countries: ["United States"],
      type: "movie",
      featured: false
    },
    // Classic Movies
    {
      title: "The Avengers",
      description: "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
      year: 2012,
      duration: 143,
      rating: 8.0,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_7mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample7",
      genres: ["Action", "Adventure", "Sci-Fi"],
      countries: ["United States"],
      type: "movie",
      featured: false
    },
    {
      title: "Avatar",
      description: "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
      year: 2009,
      duration: 162,
      rating: 7.9,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_8mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample8",
      genres: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
      countries: ["United States"],
      type: "movie",
      featured: false
    },
    {
      title: "The Dark Knight",
      description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
      year: 2008,
      duration: 152,
      rating: 9.0,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_9mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample9",
      genres: ["Action", "Crime", "Drama"],
      countries: ["United States"],
      type: "movie",
      featured: false
    },
    {
      title: "Inception",
      description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
      year: 2010,
      duration: 148,
      rating: 8.8,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_10mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample10",
      genres: ["Action", "Sci-Fi", "Thriller"],
      countries: ["United States"],
      type: "movie",
      featured: false
    },
    {
      title: "Interstellar",
      description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
      year: 2014,
      duration: 169,
      rating: 8.6,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_11mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample11",
      genres: ["Adventure", "Drama", "Sci-Fi"],
      countries: ["United States"],
      type: "movie",
      featured: false
    },
    // Korean Movies
    {
      title: "Parasite",
      description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
      year: 2019,
      duration: 132,
      rating: 8.5,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_12mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample12",
      genres: ["Comedy", "Thriller", "Drama"],
      countries: ["South Korea"],
      type: "movie",
      featured: false
    },
    {
      title: "Train to Busan",
      description: "A father and his daughter board a train heading from Seoul to Busan, but when a zombie outbreak breaks out in the country, passengers must fight for their lives.",
      year: 2016,
      duration: 118,
      rating: 7.6,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/1NgFtPJnyhIqH7dWREqPdP3FpqO.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/1NgFtPJnyhIqH7dWREqPdP3FpqO.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_13mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample13",
      genres: ["Action", "Horror", "Thriller"],
      countries: ["South Korea"],
      type: "movie",
      featured: false
    },
    {
      title: "Oldboy",
      description: "After being kidnapped and imprisoned for fifteen years, Oh Dae-Su is released, only to find that he must find his captor in five days.",
      year: 2003,
      duration: 120,
      rating: 8.4,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/pWDtjs568ZfOTMbURQBYuT4Qr7P.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/pWDtjs568ZfOTMbURQBYuT4Qr7P.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_14mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample14",
      genres: ["Action", "Drama", "Mystery"],
      countries: ["South Korea"],
      type: "movie",
      featured: false
    },
    // Japanese Movies/Anime
    {
      title: "Your Name",
      description: "Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?",
      year: 2016,
      duration: 106,
      rating: 8.4,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/q719jXXEzOoYaps6babgKnONONX.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_15mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample15",
      genres: ["Animation", "Romance", "Supernatural"],
      countries: ["Japan"],
      type: "movie",
      featured: false
    },
    {
      title: "Spirited Away",
      description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.",
      year: 2001,
      duration: 125,
      rating: 9.2,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_16mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample16",
      genres: ["Animation", "Adventure", "Family"],
      countries: ["Japan"],
      type: "movie",
      featured: false
    },
    {
      title: "Akira",
      description: "A secret military project endangers Neo-Tokyo when it turns a biker gang member into a rampaging psychic psychopath.",
      year: 1988,
      duration: 124,
      rating: 8.0,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_17mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample17",
      genres: ["Animation", "Action", "Sci-Fi"],
      countries: ["Japan"],
      type: "movie",
      featured: false
    },
    // Horror Movies
    {
      title: "The Conjuring",
      description: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
      year: 2013,
      duration: 112,
      rating: 7.5,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/wVYREutTvI2tmxr6ujrHT704wGF.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/wVYREutTvI2tmxr6ujrHT704wGF.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_18mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample18",
      genres: ["Horror", "Mystery", "Thriller"],
      countries: ["United States"],
      type: "movie",
      featured: false
    },
    {
      title: "Hereditary",
      description: "A grieving family is haunted by tragedy and disturbing secrets.",
      year: 2018,
      duration: 127,
      rating: 7.3,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/p9fmuz2Oj3XqJjcJ31dqxA7RJFe.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/p9fmuz2Oj3XqJjcJ31dqxA7RJFe.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_19mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample19",
      genres: ["Horror", "Drama", "Mystery"],
      countries: ["United States"],
      type: "movie",
      featured: false
    },
    {
      title: "Get Out",
      description: "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness becomes a nightmare.",
      year: 2017,
      duration: 104,
      rating: 7.7,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_20mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample20",
      genres: ["Horror", "Mystery", "Thriller"],
      countries: ["United States"],
      type: "movie",
      featured: false
    },
    // Action Movies
    {
      title: "Mad Max: Fury Road",
      description: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners.",
      year: 2015,
      duration: 120,
      rating: 8.1,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_21mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample21",
      genres: ["Action", "Adventure", "Sci-Fi"],
      countries: ["Australia"],
      type: "movie",
      featured: false
    },
    {
      title: "Mission: Impossible - Fallout",
      description: "Ethan Hunt and his IMF team, along with some familiar allies, race against time after a mission gone wrong.",
      year: 2018,
      duration: 147,
      rating: 7.7,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_22mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample22",
      genres: ["Action", "Adventure", "Thriller"],
      countries: ["United States"],
      type: "movie",
      featured: false
    },
    // Comedy Movies
    {
      title: "The Grand Budapest Hotel",
      description: "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy.",
      year: 2014,
      duration: 99,
      rating: 8.1,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_23mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample23",
      genres: ["Adventure", "Comedy", "Crime"],
      countries: ["Germany"],
      type: "movie",
      featured: false
    },
    {
      title: "Knives Out",
      description: "A detective investigates the death of a patriarch of an eccentric, combative family.",
      year: 2019,
      duration: 130,
      rating: 7.9,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_24mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample24",
      genres: ["Comedy", "Crime", "Drama"],
      countries: ["United States"],
      type: "movie",
      featured: false
    },
    // TV Series
    {
      title: "Breaking Bad",
      description: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
      year: 2008,
      duration: 47,
      rating: 9.5,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_25mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample25",
      genres: ["Drama", "Crime", "Thriller"],
      countries: ["United States"],
      type: "tv",
      featured: false
    },
    {
      title: "Stranger Things",
      description: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
      year: 2016,
      duration: 51,
      rating: 8.7,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_26mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample26",
      genres: ["Drama", "Fantasy", "Horror"],
      countries: ["United States"],
      type: "tv",
      featured: false
    },
    {
      title: "Game of Thrones",
      description: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
      year: 2011,
      duration: 57,
      rating: 9.2,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_27mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample27",
      genres: ["Action", "Adventure", "Drama"],
      countries: ["United States"],
      type: "tv",
      featured: false
    },
    {
      title: "The Last of Us",
      description: "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity's last hope.",
      year: 2023,
      duration: 60,
      rating: 8.7,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_28mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample28",
      genres: ["Action", "Adventure", "Drama"],
      countries: ["United States"],
      type: "tv",
      featured: false
    },
    {
      title: "The Witcher",
      description: "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.",
      year: 2019,
      duration: 60,
      rating: 8.2,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/cZ0d3rtvXPVvuiX22sP79K3Hmjz.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/cZ0d3rtvXPVvuiX22sP79K3Hmjz.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_29mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample29",
      genres: ["Action", "Adventure", "Drama"],
      countries: ["United States"],
      type: "tv",
      featured: false
    },
    {
      title: "Wednesday",
      description: "Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends — and foes — at Nevermore Academy.",
      year: 2022,
      duration: 50,
      rating: 8.1,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_30mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample30",
      genres: ["Comedy", "Crime", "Family"],
      countries: ["United States"],
      type: "tv",
      featured: false
    },
    {
      title: "House of the Dragon",
      description: "An internal succession war within House Targaryen at the height of its power, 172 years before the birth of Daenerys Targaryen.",
      year: 2022,
      duration: 68,
      rating: 8.5,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_31mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample31",
      genres: ["Action", "Adventure", "Drama"],
      countries: ["United States"],
      type: "tv",
      featured: false
    },
    {
      title: "Squid Game",
      description: "Hundreds of cash-strapped contestants accept an invitation to compete in children's games for a tempting prize, but the stakes are deadly.",
      year: 2021,
      duration: 56,
      rating: 8.0,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_32mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample32",
      genres: ["Action", "Drama", "Mystery"],
      countries: ["South Korea"],
      type: "tv",
      featured: false
    },
    {
      title: "Money Heist",
      description: "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.",
      year: 2017,
      duration: 70,
      rating: 8.2,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_33mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample33",
      genres: ["Action", "Crime", "Mystery"],
      countries: ["Spain"],
      type: "tv",
      featured: false
    },
    // More International Films
    {
      title: "Amélie",
      description: "Amélie is an innocent and naive girl in Paris with her own sense of justice. She decides to help those around her and, along the way, discovers love.",
      year: 2001,
      duration: 122,
      rating: 8.3,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/nSxDa3M9aMvGVLoItzWTepQ5h5d.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/nSxDa3M9aMvGVLoItzWTepQ5h5d.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_34mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample34",
      genres: ["Comedy", "Romance"],
      countries: ["France"],
      type: "movie",
      featured: false
    },
    {
      title: "City of God",
      description: "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.",
      year: 2002,
      duration: 130,
      rating: 8.6,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/k7eYdcdEp9rf3YmU3c2Yv4UaEHq.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/k7eYdcdEp9rf3YmU3c2Yv4UaEHq.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_35mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample35",
      genres: ["Crime", "Drama"],
      countries: ["Brazil"],
      type: "movie",
      featured: false
    },
    {
      title: "Life is Beautiful",
      description: "When an open-minded Jewish librarian and his son become victims of the Holocaust, he uses a perfect mixture of will, humor, and imagination to protect his son.",
      year: 1997,
      duration: 116,
      rating: 8.6,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/mfnkSeeVOBcGyaOTQ8h3lJBWdcj.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/mfnkSeeVOBcGyaOTQ8h3lJBWdcj.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_36mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample36",
      genres: ["Comedy", "Drama", "Romance"],
      countries: ["Italy"],
      type: "movie",
      featured: false
    },
    {
      title: "Pan's Labyrinth",
      description: "In the Falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.",
      year: 2006,
      duration: 118,
      rating: 8.2,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/kBH7lQKpYmEDJdtYh5GhM0OGNHB.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/kBH7lQKpYmEDJdtYh5GhM0OGNHB.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_37mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample37",
      genres: ["Drama", "Fantasy", "War"],
      countries: ["Spain"],
      type: "movie",
      featured: false
    },
    {
      title: "The Handmaiden",
      description: "A woman is hired as a handmaiden to a Japanese heiress, but secretly she is involved in a plot to defraud her.",
      year: 2016,
      duration: 145,
      rating: 8.1,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/dTsgvwEr5LSjnWGK8PF1dDIR6oq.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/dTsgvwEr5LSjnWGK8PF1dDIR6oq.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_38mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample38",
      genres: ["Drama", "Romance", "Thriller"],
      countries: ["South Korea"],
      type: "movie",
      featured: false
    },
    {
      title: "Roma",
      description: "A year in the life of a middle-class family's maid in Mexico City in the early 1970s.",
      year: 2018,
      duration: 135,
      rating: 7.7,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/1V8A5SgIjVdBdpQ4B2EJMZAQjJB.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/1V8A5SgIjVdBdpQ4B2EJMZAQjJB.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_39mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample39",
      genres: ["Drama"],
      countries: ["Mexico"],
      type: "movie",
      featured: false
    },
    {
      title: "The Shape of Water",
      description: "At a top secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.",
      year: 2017,
      duration: 123,
      rating: 7.3,
      quality: "HD",
      poster: "https://image.tmdb.org/t/p/w500/9zfwPffUXpBrEP26yp0q1ckXDcj.jpg",
      backdrop: "https://image.tmdb.org/t/p/w1280/9zfwPffUXpBrEP26yp0q1ckXDcj.jpg",
      play_url: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_40mb.mp4",
      trailer_url: "https://www.youtube.com/watch?v=sample40",
      genres: ["Adventure", "Drama", "Fantasy"],
      countries: ["United States"],
      type: "movie",
      featured: false
    }
  ];

  // Clear existing data first
  await db.delete(movies);

  for (const movie of sampleMovies) {
    await db.insert(movies).values(movie);
  }

  console.log(`Database seeded successfully with ${sampleMovies.length} movies and TV shows!`);
}

seed().catch(console.error);
